package com.ollacercana.domain;


public enum TipoEvento {
    RESERVA_CREADA,
    RESERVA_CONFIRMADA,
    RESERVA_RECHAZADA,
    RESERVA_EXPIRADA,
    RESERVA_CANCELADA,
    RECORDATORIO_RESERVA,
    DISPONIBILIDAD_ACTUALIZADA,
    NUEVO_MENSAJE_CHAT,
    CALIFICACION_PUBLICADA
}
