package com.ollacercana.model.domain;


public enum TipoEvento {
    RESERVA_CREADA,
    RESERVA_CONFIRMADA,
    RESERVA_RECHAZADA,
    RESERVA_EXPIRADA,
    RESERVA_CANCELADA,
    RESERVA_COMPLETADA,      // ← HU-23
    RECORDATORIO_RESERVA,    // ← RN-25
    DISPONIBILIDAD_ACTUALIZADA,
    NUEVO_MENSAJE_CHAT,
    CALIFICACION_PUBLICADA
}