spring:
  application:
    name: olla-cercana

  datasource:
    url: jdbc:postgresql://localhost:5432/olla_cercana
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update          # dev: update | prod: validate | test: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false         # buena práctica: evita warnings y lazy loading accidental

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080